# Generated by Django 4.1.4 on 2022-12-12 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('cage_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Calibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goes_to', models.IntegerField()),
                ('came_from', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FoodPortion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kg', models.FloatField()),
                ('bags', models.FloatField()),
                ('total_30_days', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Mortality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theoric_percentage', models.FloatField()),
                ('theoric_number', models.IntegerField()),
                ('real_percentage', models.FloatField()),
                ('real_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Real30Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeding', models.FloatField()),
                ('medium_weight_with_real_feeding', models.FloatField()),
                ('medium_weight', models.FloatField()),
                ('biomass', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Theoric30Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biomass_increase', models.FloatField()),
                ('biomass_total', models.FloatField()),
                ('medium_weight', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MonthStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('year', models.IntegerField()),
                ('num_fishes', models.IntegerField()),
                ('medium_weight', models.FloatField()),
                ('biomass', models.FloatField()),
                ('percent_feeding', models.FloatField()),
                ('fc', models.FloatField()),
                ('biomass_increase_with_mortality', models.IntegerField(default=None)),
                ('real_fc_with_mortality', models.FloatField()),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cage')),
                ('calibration', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.calibration')),
                ('food_portion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.foodportion')),
                ('mortality', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.mortality')),
                ('real_30_days', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.real30days')),
                ('theoric_30_days', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.theoric30days')),
            ],
        ),
    ]
