# Generated by Django 4.1.4 on 2022-12-13 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cage',
            fields=[
                ('cage_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MonthStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('temperature', models.FloatField()),
                ('year', models.IntegerField()),
                ('num_fishes', models.IntegerField()),
                ('theoric_medium_weight_with_real_feeding', models.FloatField()),
                ('medium_weight', models.FloatField()),
                ('biomass', models.FloatField()),
                ('percent_feeding', models.FloatField()),
                ('fc', models.FloatField()),
                ('biomass_increase_with_mortality', models.IntegerField(default=0)),
                ('real_fc_with_mortality', models.FloatField(default=0)),
                ('food_portion_kg', models.FloatField()),
                ('food_portion_bags', models.FloatField()),
                ('food_portion_total_30_days', models.FloatField()),
                ('theoric_30_days_biomass_increase', models.FloatField()),
                ('theoric_30_days_biomass_total', models.FloatField()),
                ('theoric_30_days_medium_weight', models.FloatField()),
                ('real_30_days_feeding', models.FloatField()),
                ('real_30_days_medium_weight_with_real_feeding', models.FloatField()),
                ('real_30_days_real_medium_weight', models.FloatField()),
                ('real_30_days_biomass', models.FloatField()),
                ('mortality_theoric_percentage', models.FloatField()),
                ('mortality_theoric_number', models.IntegerField()),
                ('mortality_real_percentage', models.FloatField()),
                ('mortality_real_number', models.IntegerField()),
                ('calibration_goes_to', models.IntegerField()),
                ('calibration_came_from', models.IntegerField()),
                ('cage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.cage')),
            ],
        ),
    ]
