# Generated by Django 4.1.4 on 2022-12-16 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthstat',
            name='calibration_came_from',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='monthstat',
            name='calibration_goes_to',
            field=models.JSONField(),
        ),
    ]
